### ISSUE TITLE
Colores y carpetas

### ISSUE THREAD

**Issue by roderKnight** [Jalgoz/Prueba-Pagina1#1]
## Sugerencias: 
1. En MaterialDesign por convención se usan dos colores con su versión en Light y Dark.
Se tiene como en el documento por default: 
`--primary: #112d4e;`
`--primaryLight: #40567a;` 
`--primaryDark: #000126;`
`--secondary: #3f72af;`
`--secondaryLight: #73a0e1;`
`--secondaryDark: #00477f;`

2. Tener directorios para los estilos **css**, para las imágenes **img**, y si se necesitara para los scripts **js**

**Comment by Jalgoz** [comment]
Gracias por añadir Rubén, pero mejor si lo haces en el README.md los issues son más para errores o problemas que existan en el proyecto

**Comment by Jalgoz** [comment]
Tu sugerencia lo pasare al README.md
